// AuthBolt.sx.template.ts
// Runtime LOCK assembler for the AuthBolt identity NFT: MinSimpleBolt (zero-funding) plus an owner-supplied
// `authOrMiscData` (<= 75 B) carried in every spend. LOCK_SCRIPT_SUFFIX / UNLOCK_SCRIPT_SUFFIX are
// auto-patched from the pre-compiled artifact by scripts/build-min-simple-bolt.mjs (build-time only) -
// do NOT hand-edit them.
//
// Lock layout (6 dynamic data args, then the static contract suffix) - identical to MinSimpleBolt:
//   pubKeyHash[20] · pubKeyHashCommitment[20] · txoType[1] · parentOutpoint[36] ·
//   grandparentOutpoint[36] · issuerPubKey[33]  +  LOCK_SCRIPT_SUFFIX
// The two contracts are told apart by the sha256 of the suffix alone (see scanner/fingerprints.ts).
//
// Unlock layout (39 args): authOrMiscData, 27 ancestor pieces (incl. Vin1AuthOrMiscData), 11 current-tx args.
// authOrMiscData is created in a commit and authenticated in the settle (which rebuilds its grandparent
// commit, whose scriptSig leads with it). The commit's own owner signature does NOT cover it.
//
// Receiving off-chain: a minted token sent by SPV does not prove the sender holds the issuer key (anyone can
// mint an output naming any issuerPubKey). The issuer guard runs when the genesis is first SPENT, so a commit
// signed by the issuer, funded or not, must accompany it. Where authOrMiscData travels, the signed commit AND
// settle must be passed together as the package (see README: "Receiving a token off-chain").
import { ScriptTemplate, LockingScript, Script, PrivateKey, Transaction, UnlockingScript } from "@bsv/sdk";
import { singleSpendUnlock } from "../../lib/single/singleSpend.js";
import type { Signer } from "../../lib/boltLib.js";
import { AUTH_BOLT_LAYOUT } from "../../lib/single/singleAncestor.js";

/** authOrMiscData is a DIRECT push (0x00..0x4b), enforced by the lock. */
export const AUTH_DATA_MAX_BYTES = 75;

export default class AuthBoltTemplate implements ScriptTemplate {
  // Static UNLOCK suffix (after the 39 data pushes), patched from the artifact - do NOT hand-edit.
  private readonly UNLOCK_SCRIPT_SUFFIX = "OP_5 OP_PICK OP_5 OP_ROLL OP_5 OP_ROLL OP_5 OP_PICK OP_5 OP_PICK OP_CAT OP_CAT OP_CAT OP_CAT OP_4 OP_ROLL OP_2 OP_ROLL OP_4 OP_ROLL OP_4 OP_ROLL OP_CAT OP_CAT OP_CAT OP_SWAP OP_IFDUP OP_IF 41 OP_TOALTSTACK OP_HASH256 OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT 00 OP_CAT OP_BIN2NUM OP_1 OP_ADD OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 022079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179802 OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 30 OP_SWAP OP_CAT OP_FROMALTSTACK OP_CAT 038ff83d8cf12121491609c4939dc11c4aa35503508fe432dc5a5c1905608b9218 OP_CODESEPARATOR OP_CHECKSIGVERIFY OP_ENDIF";
  private readonly LOCK_SCRIPT_SUFFIX = "OP_2 OP_PICK OP_BIN2NUM OP_NOT OP_SWAP OP_2SWAP OP_DUP OP_BIN2NUM OP_0NOTEQUAL OP_DUP OP_NOT OP_6 OP_PICK OP_BIN2NUM OP_BOOLAND OP_5 OP_PICK OP_BOOLOR OP_IF OP_3 OP_PICK OP_10 OP_PICK OP_EQUALVERIFY OP_ENDIF 29 OP_PICK OP_SIZE OP_NIP 4c OP_LESSTHAN OP_VERIFY OP_8 OP_PICK OP_IFDUP OP_IF OP_DUP 41 OP_TOALTSTACK OP_HASH256 OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT 00 OP_CAT OP_BIN2NUM OP_1 OP_ADD OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 022079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179802 OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 30 OP_SWAP OP_CAT OP_FROMALTSTACK OP_CAT 038ff83d8cf12121491609c4939dc11c4aa35503508fe432dc5a5c1905608b9218 OP_CHECKSIGVERIFY OP_4 OP_SPLIT 20 OP_SPLIT 20 OP_SPLIT 24 OP_SPLIT OP_1 OP_SPLIT OP_NIP OP_2 OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_8 OP_SPLIT OP_4 OP_SPLIT 20 OP_SPLIT OP_4 OP_SPLIT OP_1 OP_SPLIT OP_SWAP 41 OP_EQUALVERIFY OP_9 OP_PICK OP_2 OP_GREATERTHANOREQUAL OP_VERIFY OP_5 OP_ROLL 15 OP_SPLIT 15 OP_SPLIT OP_2 OP_SPLIT 25 OP_SPLIT 25 OP_SPLIT 22 OP_SPLIT OP_DUP OP_TOALTSTACK OP_11 OP_PICK OP_DUP OP_BIN2NUM OP_1 OP_EQUALVERIFY 16 OP_PICK OP_NOTIF 1d02b0178876a914 OP_CAT 1c OP_PICK OP_CAT 88ac OP_CAT OP_ENDIF 14 17 OP_PICK OP_NOTIF 19 OP_ELSE 18 OP_ENDIF OP_PICK OP_CAT 14 18 OP_PICK OP_NOTIF 1e OP_PICK OP_ELSE OP_0 14 OP_NUM2BIN OP_ENDIF OP_CAT OP_CAT 17 OP_PICK OP_IF 0100 OP_ELSE 0121 OP_ENDIF OP_CAT 24 OP_15 OP_PICK OP_CAT OP_CAT OP_5 OP_PICK OP_CAT 16 OP_PICK OP_IF 21 1c OP_PICK OP_CAT OP_ELSE OP_3 OP_PICK OP_ENDIF OP_CAT OP_2 OP_PICK OP_CAT fd1105 OP_DUP OP_TOALTSTACK OP_14 OP_PICK OP_SWAP OP_CAT OP_SWAP OP_CAT 17 OP_PICK OP_NOTIF OP_SWAP OP_CAT OP_ELSE OP_NIP OP_ENDIF 1d OP_PICK OP_CAT OP_HASH256 OP_10 OP_PICK OP_EQUALVERIFY OP_12 OP_PICK 16 OP_PICK OP_BIN2NUM 12 OP_PICK OP_BOOLAND OP_IF 39 OP_PICK 37 OP_PICK OP_SIZE OP_NIP OP_0NOTEQUAL OP_1ADD OP_CAT 39 OP_PICK OP_CAT 38 OP_PICK OP_SIZE OP_1 OP_NUM2BIN OP_SWAP OP_CAT OP_0 1b OP_NUM2BIN OP_CAT 38 OP_PICK OP_SIZE OP_1 OP_NUM2BIN OP_SWAP OP_CAT OP_CAT 37 OP_PICK OP_SIZE OP_1 OP_NUM2BIN OP_SWAP OP_CAT OP_CAT 36 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 35 OP_PICK OP_SIZE OP_SWAP OP_CAT OP_CAT 34 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 33 OP_PICK 4c68 OP_SWAP OP_CAT 33 OP_PICK 14 OP_SWAP OP_CAT 33 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 32 OP_PICK 01 OP_SWAP OP_CAT OP_CAT 31 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 30 OP_PICK 24 OP_SWAP OP_CAT OP_CAT OP_6 OP_PICK OP_CAT OP_5 OP_PICK OP_CAT OP_DUP ad68 OP_DUP OP_ROT OP_CAT OP_DROP 03fd1305 OP_SWAP 02 OP_SWAP OP_CAT OP_CAT OP_SWAP fd1105 03 OP_SWAP OP_CAT OP_TOALTSTACK 4d1105 OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT 2d OP_PICK 34 OP_SWAP OP_CAT OP_CAT OP_FROMALTSTACK OP_CAT 5579557a557a557955797e7e7e7e547a527a547a547a7e7e7e7c73630141 OP_CAT OP_FROMALTSTACK OP_FROMALTSTACK OP_SWAP OP_TOALTSTACK 29 OP_SPLIT OP_NIP 7d01 OP_SPLIT OP_DROP OP_CAT abad68 OP_CAT OP_SIZE OP_2 OP_NUM2BIN fd OP_SWAP OP_CAT OP_SWAP OP_CAT OP_CAT 2b OP_PICK OP_CAT 2a OP_PICK OP_CAT 29 OP_PICK OP_SIZE OP_SWAP OP_CAT OP_CAT 28 OP_PICK OP_CAT 21 OP_PICK OP_SIZE OP_NIP OP_0NOTEQUAL OP_2 OP_ADD OP_CAT OP_13 OP_PICK OP_CAT OP_FROMALTSTACK OP_CAT 27 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 26 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 25 OP_PICK 01 OP_SWAP OP_CAT OP_CAT 24 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 23 OP_PICK 24 OP_SWAP OP_CAT OP_CAT OP_3 OP_PICK OP_CAT OP_2 OP_PICK OP_CAT OP_13 OP_PICK OP_CAT 1d02b0178876a914 OP_CAT 19 OP_PICK OP_CAT 88ac OP_CAT 22 OP_PICK OP_CAT 21 OP_PICK OP_SIZE OP_SWAP OP_CAT OP_CAT 20 OP_PICK OP_CAT OP_HASH256 OP_DUP 14 OP_PICK 20 OP_SPLIT OP_DROP OP_EQUALVERIFY 01000000 OP_CAT OP_CAT OP_ELSE 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK 39 OP_PICK OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_SIZE OP_NIP OP_0 OP_EQUALVERIFY OP_ENDIF 1e OP_PICK OP_CAT OP_HASH256 OP_15 OP_PICK OP_EQUALVERIFY 1a OP_PICK OP_DUP OP_SIZE OP_1SUB OP_SPLIT OP_NIP 41 OP_EQUALVERIFY 1a OP_PICK OP_DUP OP_HASH160 1a OP_ELSE OP_10 OP_PICK OP_DUP OP_SIZE OP_1SUB OP_SPLIT OP_NIP 41 OP_EQUALVERIFY OP_10 OP_PICK OP_DUP OP_HASH160 OP_10 OP_ENDIF OP_PICK OP_EQUALVERIFY OP_CHECKSIG";

  /**
   * Build an AuthBolt locking script from its 6 contract args.
   * For a genesis identity mint: pubKeyHash = recipient, issuerPubKey = issuer,
   * pubKeyHashCommitment = zeros[20], txoType = [0x00], parent/grandparent = zeros[36].
   */
  lock(
    pubKeyHash: number[],
    issuerPubKey: number[],
    pubKeyHashCommitment: number[] = new Array(20).fill(0x00),
    txoType: number[] = [0x00],
    parentOutpoint: number[] = new Array(36).fill(0x00),
    grandparentOutpoint: number[] = new Array(36).fill(0x00),
  ): LockingScript {
    return new LockingScript([
      ...new Script().writeBin(pubKeyHash).chunks,
      ...new Script().writeBin(pubKeyHashCommitment).chunks,
      ...new Script().writeBin(txoType).chunks,
      ...new Script().writeBin(parentOutpoint).chunks,
      ...new Script().writeBin(grandparentOutpoint).chunks,
      ...new Script().writeBin(issuerPubKey).chunks,
      ...Script.fromASM(this.LOCK_SCRIPT_SUFFIX).chunks,
    ]);
  }

  /** The static contract suffix (everything after the 6 data pushes), as a Script. */
  staticSuffix(): Script {
    return Script.fromASM(this.LOCK_SCRIPT_SUFFIX);
  }

  /**
   * Spend (transfer commit/settle) this bolt, carrying `authOrMiscData`. Requires tx version >= 2.
   * @param beneficiaryPubKeyHash the next owner's 20-byte pkh
   * @param prevTxs prior lineage txs (mint, commit, ...); a back-reaching settle (>= 4 txs) reconstructs its ancestor
   * @param authOrMiscData up to 75 bytes (a direct push) bound by the settle's grandparent rebuild; [] = none (OP_0)
   * @throws if authOrMiscData is longer than 75 bytes (the lock would refuse the tx)
   */
  unlock(
    privateKey: PrivateKey | Signer,
    beneficiaryPubKeyHash: number[],
    prevTxs: Transaction[] = [],
    authOrMiscData: number[] = [],
    forceNoChange = false,
    forceNoFund = false,
  ): { sign: (tx: Transaction, inputIndex: number) => Promise<UnlockingScript>; estimateLength: () => Promise<number> } {
    if (authOrMiscData.length > AUTH_DATA_MAX_BYTES) {
      throw new Error(`authOrMiscData is ${authOrMiscData.length} bytes; the maximum is ${AUTH_DATA_MAX_BYTES} (a direct push)`);
    }
    return singleSpendUnlock({
      privateKey,
      beneficiaryPubKeyHash,
      unlockScriptSuffixASM: this.UNLOCK_SCRIPT_SUFFIX,
      prevTxs,
      forceNoChange,
      forceNoFund,
      layout: AUTH_BOLT_LAYOUT,
      authOrMiscData,
    });
  }

  /**
   * MELT (burn) this bolt: an owner spend with a null CTX and no token output. Requires tx version >= 2.
   * A token that is still a genesis mint (or its first commit) can only be melted by the issuer key.
   */
  melt(
    privateKey: PrivateKey | Signer,
  ): { sign: (tx: Transaction, inputIndex: number) => Promise<UnlockingScript>; estimateLength: () => Promise<number> } {
    return singleSpendUnlock({
      privateKey, beneficiaryPubKeyHash: [], unlockScriptSuffixASM: this.UNLOCK_SCRIPT_SUFFIX, melt: true, layout: AUTH_BOLT_LAYOUT,
    });
  }
}
