// SimpleMultiBolt.sx.template.ts
// Runtime lock/unlock script assembler for the optimised SimpleMultiBolt contract.
// The two *_SCRIPT_SUFFIX constants are auto-patched from sxFiles/SimpleMultiBolt.sx.json
// at build time (compileBoltContracts.mjs) - do NOT hand-edit them.
//
// Layout (see multiBoltLib.ts):
//   lock  = 11 data args + LOCK_SCRIPT_SUFFIX
//   unlock = 198 data args + UNLOCK_SCRIPT_SUFFIX  (no leading miscData; 5 interop args)

import {
  ScriptTemplate,
  LockingScript,
  Script,
  PrivateKey,
  UnlockingScript,
  Transaction,
  TransactionSignature,
  Hash,
  Utils,
} from "@bsv/sdk";
import { splitCtx, buildOutpoint, buildChangeOutput, createSignature, scriptChunksFromBin } from "../../lib/boltLib.js";
import {
  ancestorPiece,
  createEmptyFungibleAncestorChunksSMB,
  PIECE_NAMES,
} from "../../lib/multi/multiBoltLib.js";

export default class SimpleMultiTemplate implements ScriptTemplate {
  private signatureScope = TransactionSignature.SIGHASH_FORKID | TransactionSignature.SIGHASH_ALL;

  private readonly LOCK_SCRIPT_SUFFIX = "OP_2 OP_PICK OP_BIN2NUM OP_NOT OP_TUCK OP_IF OP_13 OP_PICK OP_EQUALVERIFY OP_15 OP_PICK OP_DUP 25 OP_EQUAL OP_NOT OP_VERIFY 27 OP_EQUAL OP_NOT OP_VERIFY OP_ELSE OP_DROP OP_ENDIF OP_SWAP OP_DUP OP_BIN2NUM OP_0NOTEQUAL OP_12 OP_PICK OP_IFDUP OP_IF OP_DUP 41 OP_TOALTSTACK OP_HASH256 OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT 00 OP_CAT OP_BIN2NUM OP_1 OP_ADD OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 022079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179802 OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 30 OP_SWAP OP_CAT OP_FROMALTSTACK OP_CAT 038ff83d8cf12121491609c4939dc11c4aa35503508fe432dc5a5c1905608b9218 OP_CHECKSIGVERIFY OP_4 OP_SPLIT 20 OP_SPLIT 20 OP_SPLIT 24 OP_SPLIT OP_1 OP_SPLIT OP_SWAP OP_DUP ff OP_EQUAL OP_IF OP_DROP OP_8 OP_SPLIT OP_SWAP OP_ELSE OP_DUP fe OP_EQUAL OP_IF OP_DROP OP_4 OP_SPLIT OP_SWAP OP_ELSE OP_DUP fd OP_EQUAL OP_IF OP_DROP OP_2 OP_SPLIT OP_SWAP OP_ELSE 00 OP_CAT OP_ENDIF OP_ENDIF OP_ENDIF OP_BIN2NUM OP_SPLIT OP_8 OP_SPLIT OP_4 OP_SPLIT 20 OP_SPLIT OP_4 OP_SPLIT OP_1 OP_SPLIT OP_SWAP 41 OP_EQUALVERIFY OP_9 OP_PICK OP_2 OP_GREATERTHANOREQUAL OP_VERIFY OP_5 OP_ROLL 11 OP_SPLIT 11 OP_SPLIT 15 OP_SPLIT 15 OP_SPLIT 15 OP_SPLIT 25 OP_SPLIT OP_2 OP_SPLIT OP_2 OP_SPLIT 25 OP_SPLIT 25 OP_SPLIT 22 OP_SPLIT 1a OP_PICK OP_2 OP_MOD OP_DUP OP_IF 26 OP_PICK OP_1ADD 1c OP_PICK OP_EQUALVERIFY OP_ENDIF OP_DUP 27 OP_PICK OP_2 OP_MOD OP_SWAP OP_IF OP_0 OP_ELSE OP_1 OP_ENDIF OP_EQUALVERIFY 1d02b0178876a914 ffffffffffffffffffffffffffffff7f 10 OP_0 OP_16 OP_NUM2BIN OP_CAT 14 OP_0 14 OP_NUM2BIN OP_CAT 21 OP_0 21 OP_NUM2BIN OP_CAT 24 OP_0 24 OP_NUM2BIN OP_CAT 27 OP_PICK OP_DUP OP_0 OP_GREATERTHANOREQUAL OP_VERIFY OP_5 OP_PICK OP_LESSTHANOREQUAL OP_VERIFY 2d OP_PICK OP_DUP OP_0 OP_GREATERTHANOREQUAL OP_VERIFY OP_5 OP_PICK OP_LESSTHANOREQUAL OP_VERIFY 2c OP_PICK OP_DUP 20 OP_EQUAL OP_SWAP OP_DUP 21 OP_EQUAL OP_SWAP OP_DUP 22 OP_EQUAL OP_SWAP OP_DUP 23 OP_EQUAL OP_SWAP OP_DUP 24 OP_EQUAL OP_SWAP 25 OP_EQUAL 1d OP_PICK OP_BIN2NUM OP_1 OP_EQUALVERIFY OP_0 OP_PICK OP_IF 2d OP_PICK 32 OP_PICK OP_ADD OP_11 OP_PICK OP_LESSTHANOREQUAL OP_VERIFY OP_ENDIF OP_2 OP_PICK OP_IF 2c OP_PICK 32 OP_PICK OP_2DUP OP_SUB OP_0 OP_GREATERTHANOREQUAL OP_VERIFY OP_GREATERTHANOREQUAL OP_VERIFY OP_ENDIF OP_12 OP_PICK OP_NOTIF 1d OP_PICK OP_12 OP_PICK OP_CAT OP_DUP 37 OP_PICK OP_CAT 88ac OP_CAT OP_4 OP_PICK OP_IF OP_SWAP 36 OP_PICK OP_CAT 88ac OP_CAT 33 OP_PICK OP_BIN2NUM OP_IF OP_SWAP OP_ENDIF OP_CAT OP_ELSE OP_NIP OP_ENDIF OP_ELSE ff OP_ENDIF OP_5 OP_PICK OP_7 OP_PICK OP_BOOLOR OP_IF 19 OP_PICK OP_11 OP_PICK OP_CAT OP_ELSE OP_1 OP_PICK OP_4 OP_PICK OP_BOOLOR OP_IF 19 OP_PICK 10 36 OP_PICK OP_CAT OP_1 OP_PICK 35 OP_PICK OP_BIN2NUM OP_BOOLAND OP_IF OP_SWAP OP_ENDIF OP_CAT OP_ELSE OP_2 OP_PICK OP_IF 10 2f OP_PICK 2f OP_PICK OP_ADD OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_CAT OP_11 OP_PICK OP_CAT OP_ELSE OP_4 OP_PICK OP_IF 10 2f OP_PICK 2f OP_PICK OP_SUB OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_SIZE OP_16 OP_LESSTHAN OP_IF 00 OP_CAT OP_ENDIF OP_CAT OP_11 OP_PICK OP_CAT OP_ENDIF OP_ENDIF OP_ENDIF OP_ENDIF OP_6 OP_PICK OP_IF 18 OP_PICK OP_CAT 14 38 OP_PICK OP_CAT OP_CAT OP_10 OP_PICK OP_ELSE OP_7 OP_PICK OP_4 OP_PICK OP_BOOLOR OP_6 OP_PICK OP_BOOLOR OP_IF 17 OP_PICK OP_CAT OP_10 OP_PICK OP_DUP OP_CAT OP_ELSE OP_4 OP_PICK OP_IF 18 OP_PICK OP_CAT 14 38 OP_PICK OP_CAT 14 38 OP_PICK OP_CAT OP_CAT OP_ELSE OP_2 OP_PICK OP_IF 33 OP_PICK OP_BIN2NUM OP_NOTIF 18 OP_PICK OP_ELSE 14 3d OP_PICK OP_CAT OP_ENDIF OP_CAT 14 38 OP_PICK OP_CAT OP_CAT OP_10 OP_PICK OP_ENDIF OP_ENDIF OP_ENDIF OP_ENDIF OP_CAT OP_6 OP_PICK OP_8 OP_PICK OP_BOOLOR OP_4 OP_PICK OP_BOOLOR OP_5 OP_PICK OP_BOOLOR OP_6 OP_PICK OP_BOOLOR OP_IF OP_8 OP_PICK OP_CAT OP_ELSE OP_1 OP_PICK OP_IF 33 OP_PICK OP_BIN2NUM OP_NOTIF 24 3b OP_PICK OP_CAT OP_CAT OP_ELSE 12 OP_PICK OP_CAT OP_ENDIF OP_ENDIF OP_ENDIF 01 35 OP_PICK OP_CAT OP_CAT OP_2 OP_PICK 34 OP_PICK OP_BIN2NUM OP_BOOLAND OP_IF 0100 OP_CAT 24 3c OP_PICK OP_CAT OP_CAT 24 3b OP_PICK OP_CAT OP_CAT OP_ELSE 33 OP_PICK OP_BIN2NUM OP_NOTIF 0100 OP_ELSE 0101 OP_ENDIF OP_CAT 24 21 OP_PICK OP_CAT OP_CAT 12 OP_PICK OP_CAT OP_ENDIF OP_16 OP_PICK OP_CAT OP_15 OP_PICK OP_CAT OP_SIZE fd OP_SWAP OP_CAT OP_TUCK 21 OP_PICK OP_SWAP OP_CAT OP_SWAP OP_CAT OP_6 OP_PICK OP_IF 1a OP_PICK OP_13 OP_PICK OP_CAT OP_7 OP_PICK OP_NOTIF 19 OP_ELSE 18 OP_ENDIF OP_PICK OP_CAT OP_12 OP_PICK OP_DUP OP_CAT OP_CAT OP_10 OP_PICK OP_CAT 01 37 OP_PICK OP_CAT OP_CAT 39 OP_PICK OP_BIN2NUM OP_NOTIF 0101 OP_ELSE 0100 OP_ENDIF OP_CAT 24 23 OP_PICK OP_CAT OP_CAT 14 OP_PICK OP_CAT 12 OP_PICK OP_CAT 11 OP_PICK OP_CAT OP_2 OP_PICK 22 OP_PICK OP_SWAP OP_CAT OP_SWAP OP_CAT 35 OP_PICK OP_BIN2NUM OP_IF OP_SWAP OP_ENDIF OP_CAT OP_ENDIF OP_2 OP_ROLL OP_15 OP_PICK OP_NOTIF OP_CAT OP_ELSE OP_DROP OP_ENDIF 38 OP_PICK OP_CAT OP_HASH256 1d OP_PICK OP_EQUALVERIFY 1f OP_PICK OP_2 OP_PICK OP_IF 3b OP_PICK 34 OP_PICK OP_BIN2NUM OP_IF OP_SWAP OP_ENDIF OP_CAT OP_ENDIF OP_14 OP_PICK 25 OP_PICK OP_BOOLAND OP_IF f000 OP_PICK OP_SIZE OP_4 OP_EQUALVERIFY d300 OP_PICK OP_0NOTEQUAL OP_DUP OP_IF OP_3 OP_ELSE OP_2 OP_ENDIF OP_2 OP_ROLL OP_SWAP OP_CAT f100 OP_PICK OP_CAT OP_0 b200 OP_NUM2BIN OP_DUP OP_TOALTSTACK f100 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT f000 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ef00 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ee00 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ed00 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ec00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT eb00 OP_PICK 22 OP_SWAP OP_CAT OP_CAT ea00 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e900 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e800 OP_PICK OP_16 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e700 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e600 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e500 OP_PICK OP_SIZE OP_DUP 46 4b OP_WITHIN OP_VERIFY OP_SWAP OP_CAT OP_CAT e400 OP_PICK 21 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT e300 OP_PICK OP_SIZE OP_DUP 68 OP_EQUALVERIFY 4c OP_SWAP OP_1 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT e300 OP_PICK 10 OP_SWAP OP_CAT e300 OP_PICK 10 OP_SWAP OP_CAT OP_CAT e200 OP_PICK 14 OP_SWAP OP_CAT OP_CAT e100 OP_PICK 14 OP_SWAP OP_CAT OP_CAT e000 OP_PICK 14 OP_SWAP OP_CAT OP_CAT df00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT de00 OP_PICK 01 OP_SWAP OP_CAT OP_CAT dd00 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT dc00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT db00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT da00 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 14 OP_PICK OP_CAT OP_DUP OP_SIZE OP_2 OP_ADD OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_NIP 02ad68 OP_CAT OP_SWAP OP_SIZE OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_TOALTSTACK OP_SIZE OP_2 OP_NUM2BIN 4d OP_SWAP OP_CAT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT d700 OP_PICK OP_SIZE OP_DUP 34 OP_EQUALVERIFY OP_SWAP OP_CAT OP_CAT OP_FROMALTSTACK OP_CAT 5579557a557a557955797e7e7e7e547a527a547a547a7e7e7e7c73630141 13 OP_PICK 24 OP_SPLIT OP_NIP 7d01 OP_SPLIT OP_DROP OP_CAT abad68 OP_CAT OP_DUP OP_TOALTSTACK OP_CAT OP_SIZE fd OP_SWAP OP_2 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT OP_CAT d500 OP_PICK OP_CAT OP_SWAP OP_IF d300 OP_PICK OP_CAT OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK d300 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT d200 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT d100 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT d000 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT cf00 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ce00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT cd00 OP_PICK 22 OP_SWAP OP_CAT OP_CAT cc00 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT cb00 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ca00 OP_PICK OP_16 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT c900 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT c800 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT c700 OP_PICK OP_SIZE OP_DUP 46 4b OP_WITHIN OP_VERIFY OP_SWAP OP_CAT OP_CAT c600 OP_PICK 21 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT c500 OP_PICK OP_SIZE OP_DUP 68 OP_EQUALVERIFY 4c OP_SWAP OP_1 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT c500 OP_PICK 10 OP_SWAP OP_CAT c500 OP_PICK 10 OP_SWAP OP_CAT OP_CAT c400 OP_PICK 14 OP_SWAP OP_CAT OP_CAT c300 OP_PICK 14 OP_SWAP OP_CAT OP_CAT c200 OP_PICK 14 OP_SWAP OP_CAT OP_CAT c100 OP_PICK 24 OP_SWAP OP_CAT OP_CAT c000 OP_PICK 01 OP_SWAP OP_CAT OP_CAT bf00 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT be00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT bd00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT bc00 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 13 OP_PICK OP_CAT OP_DUP OP_SIZE OP_2 OP_ADD OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_NIP 02ad68 OP_CAT OP_SWAP OP_SIZE OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_TOALTSTACK OP_SIZE OP_2 OP_NUM2BIN 4d OP_SWAP OP_CAT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT b900 OP_PICK OP_SIZE OP_DUP 34 OP_EQUALVERIFY OP_SWAP OP_CAT OP_CAT OP_FROMALTSTACK OP_CAT OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_CAT OP_SIZE fd OP_SWAP OP_2 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT OP_CAT b700 OP_PICK OP_CAT OP_ENDIF b600 OP_PICK OP_CAT b500 OP_PICK OP_SIZE OP_SWAP OP_CAT OP_CAT b400 OP_PICK OP_CAT a600 OP_PICK OP_0NOTEQUAL 9d00 OP_PICK OP_0NOTEQUAL OP_2DUP OP_BOOLAND OP_IF OP_5 OP_ELSE OP_2DUP OP_BOOLOR OP_IF OP_4 OP_ELSE OP_3 OP_ENDIF OP_ENDIF OP_3 OP_ROLL OP_SWAP OP_CAT 22 OP_PICK OP_CAT OP_4 OP_PICK OP_CAT b500 OP_PICK 10 OP_SWAP OP_CAT OP_CAT b400 OP_PICK 10 OP_SWAP OP_CAT OP_CAT b300 OP_PICK 14 OP_SWAP OP_CAT OP_CAT b200 OP_PICK 14 OP_SWAP OP_CAT OP_CAT b100 OP_PICK 14 OP_SWAP OP_CAT OP_CAT b000 OP_PICK 24 OP_SWAP OP_CAT OP_CAT af00 OP_PICK 01 OP_SWAP OP_CAT OP_CAT ae00 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT ad00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT ac00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT ab00 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 12 OP_PICK OP_CAT OP_2 OP_ROLL OP_IF 20 OP_PICK OP_CAT OP_2 OP_PICK OP_CAT a800 OP_PICK 10 OP_SWAP OP_CAT OP_CAT a700 OP_PICK 10 OP_SWAP OP_CAT OP_CAT a600 OP_PICK 14 OP_SWAP OP_CAT OP_CAT a500 OP_PICK 14 OP_SWAP OP_CAT OP_CAT a400 OP_PICK 14 OP_SWAP OP_CAT OP_CAT a300 OP_PICK 24 OP_SWAP OP_CAT OP_CAT a200 OP_PICK 01 OP_SWAP OP_CAT OP_CAT a100 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT a000 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 9f00 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 9e00 OP_PICK 21 OP_SWAP OP_CAT OP_CAT OP_16 OP_PICK OP_CAT OP_ENDIF 21 OP_PICK OP_CAT OP_15 OP_PICK OP_CAT 9e00 OP_PICK OP_CAT 88ac OP_CAT OP_SWAP OP_IF 20 OP_PICK OP_CAT OP_14 OP_PICK OP_CAT 9c00 OP_PICK OP_CAT 88ac OP_CAT OP_ENDIF 9b00 OP_PICK OP_CAT 9a00 OP_PICK 19 OP_SWAP OP_CAT OP_CAT 9900 OP_PICK OP_CAT OP_HASH256 OP_DUP 27 OP_PICK 20 OP_SPLIT OP_DROP OP_EQUALVERIFY 3f OP_PICK OP_CAT OP_4 OP_PICK OP_IF 9800 OP_PICK OP_SIZE OP_4 OP_EQUALVERIFY 7b OP_PICK OP_0NOTEQUAL OP_DUP OP_IF OP_3 OP_ELSE OP_2 OP_ENDIF OP_2 OP_ROLL OP_SWAP OP_CAT 9900 OP_PICK OP_CAT OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK 9900 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9800 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9700 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9600 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9500 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9400 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 9300 OP_PICK 22 OP_SWAP OP_CAT OP_CAT 9200 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9100 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 9000 OP_PICK OP_16 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 8f00 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 8e00 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 8d00 OP_PICK OP_SIZE OP_DUP 46 4b OP_WITHIN OP_VERIFY OP_SWAP OP_CAT OP_CAT 8c00 OP_PICK 21 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 8b00 OP_PICK OP_SIZE OP_DUP 68 OP_EQUALVERIFY 4c OP_SWAP OP_1 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT 8b00 OP_PICK 10 OP_SWAP OP_CAT 8b00 OP_PICK 10 OP_SWAP OP_CAT OP_CAT 8a00 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 8900 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 8800 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 8700 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 8600 OP_PICK 01 OP_SWAP OP_CAT OP_CAT 8500 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 8400 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 8300 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 8200 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 15 OP_PICK OP_CAT OP_DUP OP_SIZE OP_2 OP_ADD OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_NIP 02ad68 OP_CAT OP_SWAP OP_SIZE OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_TOALTSTACK OP_SIZE OP_2 OP_NUM2BIN 4d OP_SWAP OP_CAT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT 7f OP_PICK OP_SIZE OP_DUP 34 OP_EQUALVERIFY OP_SWAP OP_CAT OP_CAT OP_FROMALTSTACK OP_CAT OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_CAT OP_SIZE fd OP_SWAP OP_2 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT OP_CAT 7d OP_PICK OP_CAT OP_SWAP OP_IF 7a OP_PICK OP_CAT OP_FROMALTSTACK OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_SWAP OP_TOALTSTACK 79 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 78 OP_PICK OP_4 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 77 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 76 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 75 OP_PICK 24 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 74 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 73 OP_PICK 22 OP_SWAP OP_CAT OP_CAT 72 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 71 OP_PICK 14 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 70 OP_PICK OP_16 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 6f OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 6e OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 6d OP_PICK OP_SIZE OP_DUP 46 4b OP_WITHIN OP_VERIFY OP_SWAP OP_CAT OP_CAT 6c OP_PICK 21 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 6b OP_PICK OP_SIZE OP_DUP 68 OP_EQUALVERIFY 4c OP_SWAP OP_1 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT 69 OP_PICK 10 OP_SWAP OP_CAT 69 OP_PICK 10 OP_SWAP OP_CAT OP_CAT 68 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 67 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 66 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 65 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 64 OP_PICK 01 OP_SWAP OP_CAT OP_CAT 63 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 62 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 61 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 60 OP_PICK 21 OP_SWAP OP_CAT OP_CAT OP_16 OP_PICK OP_CAT OP_DUP OP_SIZE OP_2 OP_ADD OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_NIP 02ad68 OP_CAT OP_SWAP OP_SIZE OP_2 OP_NUM2BIN 03fd OP_SWAP OP_CAT OP_TOALTSTACK OP_SIZE OP_2 OP_NUM2BIN 4d OP_SWAP OP_CAT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT 5f OP_PICK OP_SIZE OP_DUP 34 OP_EQUALVERIFY OP_SWAP OP_CAT OP_CAT OP_FROMALTSTACK OP_CAT OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_CAT OP_SIZE fd OP_SWAP OP_2 OP_1ADD OP_NUM2BIN OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_CAT OP_SWAP OP_CAT OP_CAT 5e OP_PICK OP_CAT OP_ENDIF 5e OP_PICK OP_CAT 5d OP_PICK OP_SIZE OP_SWAP OP_CAT OP_CAT 5c OP_PICK OP_CAT 4e OP_PICK OP_0NOTEQUAL 45 OP_PICK OP_0NOTEQUAL OP_2DUP OP_BOOLAND OP_IF OP_5 OP_ELSE OP_2DUP OP_BOOLOR OP_IF OP_4 OP_ELSE OP_3 OP_ENDIF OP_ENDIF OP_3 OP_ROLL OP_SWAP OP_CAT 23 OP_PICK OP_CAT OP_5 OP_PICK OP_CAT 5d OP_PICK 10 OP_SWAP OP_CAT OP_CAT 5c OP_PICK 10 OP_SWAP OP_CAT OP_CAT 5b OP_PICK 14 OP_SWAP OP_CAT OP_CAT 5a OP_PICK 14 OP_SWAP OP_CAT OP_CAT 59 OP_PICK 14 OP_SWAP OP_CAT OP_CAT 58 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 57 OP_PICK 01 OP_SWAP OP_CAT OP_CAT 56 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 55 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 54 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 53 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 13 OP_PICK OP_CAT OP_2 OP_ROLL OP_IF 21 OP_PICK OP_CAT OP_3 OP_PICK OP_CAT 50 OP_PICK 10 OP_SWAP OP_CAT OP_CAT 4f OP_PICK 10 OP_SWAP OP_CAT OP_CAT 4e OP_PICK 14 OP_SWAP OP_CAT OP_CAT 4d OP_PICK 14 OP_SWAP OP_CAT OP_CAT 4c OP_PICK 14 OP_SWAP OP_CAT OP_CAT 4b OP_PICK 24 OP_SWAP OP_CAT OP_CAT 4a OP_PICK 01 OP_SWAP OP_CAT OP_CAT 49 OP_PICK OP_1 OP_SWAP OP_SIZE OP_ROT OP_EQUAL OP_IF OP_SIZE OP_SWAP OP_CAT OP_ELSE OP_DROP 00 OP_ENDIF OP_CAT 48 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 47 OP_PICK 24 OP_SWAP OP_CAT OP_CAT 46 OP_PICK 21 OP_SWAP OP_CAT OP_CAT 11 OP_PICK OP_CAT OP_ENDIF 22 OP_PICK OP_CAT OP_16 OP_PICK OP_CAT 46 OP_PICK OP_CAT 88ac OP_CAT OP_SWAP OP_IF 20 OP_PICK OP_CAT OP_14 OP_PICK OP_CAT 43 OP_PICK OP_CAT 88ac OP_CAT OP_ENDIF 43 OP_PICK OP_CAT 42 OP_PICK 19 OP_SWAP OP_CAT OP_CAT 41 OP_PICK OP_CAT OP_HASH256 OP_DUP 2d OP_PICK 20 OP_SPLIT OP_DROP OP_EQUALVERIFY 3f OP_PICK OP_CAT 2a OP_PICK OP_BIN2NUM OP_IF OP_SWAP OP_ENDIF OP_CAT OP_ENDIF OP_CAT OP_ELSE f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK f000 OP_PICK OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_SIZE OP_NIP OP_0 OP_EQUALVERIFY OP_ENDIF 39 OP_PICK OP_CAT OP_HASH256 22 OP_PICK OP_EQUALVERIFY 31 OP_PICK OP_DUP OP_SIZE OP_1SUB OP_SPLIT OP_NIP 41 OP_EQUALVERIFY 31 OP_PICK OP_DUP OP_HASH160 2f OP_ELSE OP_14 OP_PICK OP_DUP OP_SIZE OP_1SUB OP_SPLIT OP_NIP 41 OP_EQUALVERIFY OP_14 OP_PICK OP_DUP OP_HASH160 OP_12 OP_ENDIF OP_PICK OP_EQUALVERIFY OP_CHECKSIG";
  private readonly UNLOCK_SCRIPT_SUFFIX = "OP_5 OP_PICK OP_5 OP_ROLL OP_5 OP_ROLL OP_5 OP_PICK OP_5 OP_PICK OP_CAT OP_CAT OP_CAT OP_CAT OP_4 OP_ROLL OP_2 OP_ROLL OP_4 OP_ROLL OP_4 OP_ROLL OP_CAT OP_CAT OP_CAT OP_SWAP OP_IFDUP OP_IF 41 OP_TOALTSTACK OP_HASH256 OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_1 OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT 00 OP_CAT OP_BIN2NUM OP_1 OP_ADD OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_DUP OP_0NOTEQUAL OP_SPLIT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 022079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179802 OP_SWAP OP_CAT OP_SIZE OP_SWAP OP_CAT 30 OP_SWAP OP_CAT OP_FROMALTSTACK OP_CAT 038ff83d8cf12121491609c4939dc11c4aa35503508fe432dc5a5c1905608b9218 OP_CODESEPARATOR OP_CHECKSIGVERIFY OP_ENDIF";

  private extractInputInfo(tx: Transaction, inputIndex: number, providedSatoshis?: number, providedLockingScript?: Script) {
    const input = tx.inputs[inputIndex];
    const sourceTXID = input.sourceTXID || input.sourceTransaction?.id("hex");
    if (!sourceTXID) throw new Error("The input sourceTXID or sourceTransaction is required for transaction signing.");
    const sourceSatoshis = providedSatoshis ?? input.sourceTransaction?.outputs[input.sourceOutputIndex].satoshis;
    if (!sourceSatoshis) throw new Error("The sourceSatoshis or input sourceTransaction is required for transaction signing.");
    const lockingScript = providedLockingScript ?? input.sourceTransaction?.outputs[input.sourceOutputIndex].lockingScript;
    if (!lockingScript) throw new Error("The lockingScript or input sourceTransaction is required for transaction signing.");
    const otherInputs = tx.inputs.filter((_: any, index: number) => index !== inputIndex);
    return { input, sourceTXID, sourceSatoshis, lockingScript, otherInputs };
  }

  private buildFundAndChangeOutputs(tx: Transaction, forceNoChange: boolean = false, forceNoFund: boolean = false) {
    const fundInput = tx.inputs[tx.inputs.length - 1];
    const fundOutpoint = forceNoFund ? [] : buildOutpoint(fundInput.sourceTransaction!, fundInput.sourceOutputIndex);
    const changeOutput = forceNoChange ? [] : buildChangeOutput(tx, tx.outputs.length - 1);
    return { fundOutpoint, changeOutput };
  }

  // 11 locking data args: balance, balanceCommit, pubKeyHash, pubKeyHashCommit, pubKeyHashCommit2,
  // otherGrandparentOutpoint, txoType, outputIndexN, parentOutpoint, grandparentOutpoint, issuerPubKey
  lock(
    toPubKey: number[],
    prevTxs: Transaction[],
    balance: number[] = new Array(16).fill(0x00),
    balanceCommit: number[] = new Array(16).fill(0x00),
    pubKeyHashCommit: number[] = new Array(20).fill(0x00),
    pubKeyHashCommit2: number[] = new Array(20).fill(0x00),
    otherGrandparentOutpoint: number[] = new Array(36).fill(0x00),
    txoType: number[] = [0x20],
    outputIndexN: number[] = [0x00],
    prevVoutIdx: number = 0
  ): LockingScript {
    const isGenesis = prevTxs.length === 0;
    const prevTx = prevTxs.slice(-1)[0];
    const prevTokenOutputChunks = prevTx?.outputs[prevVoutIdx].lockingScript.chunks;
    const pubKeyHash = Hash.hash160(toPubKey);

    // parentOutpoint = this token's immediate parent (prevTx:prevVoutIdx)
    const writer = new Utils.Writer();
    writer.write(Utils.toArray(prevTx?.hash() || new Array(32).fill(0x00), "hex"));
    writer.writeUInt32LE(prevVoutIdx);
    const parentOutpoint: number[] = writer.toArray();

    // grandparentOutpoint = prev token's parentOutpoint (SMB lock chunk idx 8)
    const grandparentOutpoint: number[] = (prevTokenOutputChunks?.[8].data as number[]) || new Array(36).fill(0x00);

    // issuerPubKey: toPubKey for genesis, else prev token's issuerPubKey (SMB lock chunk idx 10)
    const issuerPubKey: number[] = isGenesis ? toPubKey : (prevTokenOutputChunks?.[10].data as number[]);

    const lockingScript = new LockingScript([
      ...new Script().writeBin(balance).chunks,
      ...new Script().writeBin(balanceCommit).chunks,
      ...new Script().writeBin(pubKeyHash).chunks,
      ...new Script().writeBin(pubKeyHashCommit).chunks,
      ...new Script().writeBin(pubKeyHashCommit2).chunks,
      ...new Script().writeBin(otherGrandparentOutpoint).chunks,
      ...new Script().writeBin(txoType).chunks,
      ...new Script().writeBin(outputIndexN).chunks,
      ...new Script().writeBin(parentOutpoint).chunks,
      ...new Script().writeBin(grandparentOutpoint).chunks,
      ...new Script().writeBin(issuerPubKey).chunks,
      ...Script.fromASM(this.LOCK_SCRIPT_SUFFIX).chunks,
    ]);
    return lockingScript;
  }

  /** The static contract suffix (everything after the 11 data pushes), as a Script. */
  staticSuffix(): Script {
    return Script.fromASM(this.LOCK_SCRIPT_SUFFIX);
  }

  unlock(
    privateKey: PrivateKey,
    toPubKey: number[],
    prevTxs: Transaction[],
    forceNoChange: boolean = false,
    forceNoFund: boolean = false,
    nextBalanceCommit: number[] = new Array(16).fill(0x00),
    nextTxoType: number[] = [0x21],
    inputIndexN: number[] = [0x00],
    pubKeyHash2: number[] = [],
    grandparentBoltVoutIdx: number[] = [],
    interopBoltVoutIdx: number[] = [],
    interopPubKeyHash: number[] = [],
    interopOutpoint: number[] = [],
    interopParentOutpoint: number[] = [],
    ancestorTxBRef?: Transaction | null,
  ): {
    sign: (tx: Transaction, inputIndex: number) => Promise<UnlockingScript>;
    estimateLength: () => Promise<number>;
  } {
    return {
      sign: async (tx: Transaction, inputIndex: number) => {
        const { input, sourceTXID, sourceSatoshis, lockingScript, otherInputs } = this.extractInputInfo(tx, inputIndex);
        // SimpleMultiBolt's lock tail uses the combined OP_CHECKSIGVERIFY (ad) -> a 2-byte
        // unlock-script-code prefix.
        const ocsSubScript = new Script(Script.fromASM('OP_CHECKSIGVERIFY OP_ENDIF').chunks.concat(lockingScript.chunks));
        const ctx = TransactionSignature.format({
          sourceTXID,
          sourceOutputIndex: input.sourceOutputIndex,
          sourceSatoshis,
          transactionVersion: tx.version,
          otherInputs,
          inputIndex,
          outputs: tx.outputs,
          inputSequence: input.sequence as number,
          subscript: ocsSubScript,
          lockTime: tx.lockTime,
          scope: this.signatureScope,
        });

        const { ctxHeader, ctxCodeLen, ctxCodeUnlockScriptCode, ctxCodeLockScriptCode, ctxFooter, ctxCodeLockLen } = splitCtx(ctx, 2);
        const ctxForSig = ctxHeader.concat(...[ctxCodeLockLen, ctxCodeLockScriptCode, ctxFooter]);
        const { sigForScript, pubkeyForScript } = createSignature(privateKey, ctxForSig, this.signatureScope);
        // pubKeyHash1: empty when toPubKey is empty (split settle derives recipients from
        // the committed pubKeyHashCommit/Commit2, so pubKeyHash1 must be empty).
        const toPubKeyHash = (toPubKey && (toPubKey as number[]).length) ? Hash.hash160(toPubKey as number[]) : [];
        const txIdx = prevTxs.length;
        const { fundOutpoint, changeOutput } = this.buildFundAndChangeOutputs(tx, forceNoChange, forceNoFund);

        // ancestorTxA: present for settle txs that reach back to a prior token (idx-3, even txIdx >= 4)
        const ancestorIdx = txIdx - 3;
        const hasAncestor = ancestorIdx >= 1 && txIdx >= 4 && txIdx % 2 === 0;
        const ancestorTx = hasAncestor ? Transaction.fromHex(prevTxs[ancestorIdx].toHex()) : null;

        // ancestorTxA pieces (89)
        const ancestorAChunks: any[] = [];
        for (const piece of PIECE_NAMES) {
          ancestorAChunks.push(...scriptChunksFromBin(ancestorTx ? ancestorPiece(piece, ancestorTx) : []));
        }

        // ancestorTxB pieces (89) - populated for merge settles, empty otherwise
        const ancestorBTx = ancestorTxBRef ? Transaction.fromHex(ancestorTxBRef.toHex()) : null;
        const ancestorBChunks: any[] = [];
        for (const piece of PIECE_NAMES) {
          ancestorBChunks.push(...scriptChunksFromBin(ancestorBTx ? ancestorPiece(piece, ancestorBTx) : []));
        }

        const unlockingScript = new UnlockingScript([
          // ancestorTxA (89), ancestorTxB (89) - no leading miscData in SimpleMultiBolt
          ...ancestorAChunks,
          ...ancestorBChunks,
          // 5 interop args (empty for transfer/split; set for merge)
          ...scriptChunksFromBin(grandparentBoltVoutIdx),
          ...scriptChunksFromBin(interopBoltVoutIdx),
          ...scriptChunksFromBin(interopPubKeyHash),
          ...scriptChunksFromBin(interopOutpoint),
          ...scriptChunksFromBin(interopParentOutpoint),
          // fundOutpoint, changeOutput (both mandatory in SimpleMultiBolt)
          ...scriptChunksFromBin(fundOutpoint),
          ...scriptChunksFromBin(changeOutput),
          // pubKeyHash1, pubKeyHash2
          ...scriptChunksFromBin(toPubKeyHash),
          ...scriptChunksFromBin(pubKeyHash2),
          // nextBalanceCommit (16B), nextTxoType, inputIndexN
          ...scriptChunksFromBin(nextBalanceCommit),
          ...scriptChunksFromBin(nextTxoType),
          ...scriptChunksFromBin(inputIndexN),
          // sig, pubKey
          ...scriptChunksFromBin(sigForScript),
          ...scriptChunksFromBin(pubkeyForScript),
          // 6 CTX pieces
          ...scriptChunksFromBin(ctxHeader),
          ...scriptChunksFromBin(ctxCodeLen),
          ...scriptChunksFromBin(ctxCodeUnlockScriptCode),
          ...scriptChunksFromBin(ctxCodeLockScriptCode),
          ...scriptChunksFromBin(ctxFooter),
          ...scriptChunksFromBin(ctxCodeLockLen),
          // Compiled script logic
          ...Script.fromASM(this.UNLOCK_SCRIPT_SUFFIX).chunks,
        ]);

        return unlockingScript;
      },

      estimateLength: async () => {
        return 2000;
      },
    };
  }

  melt(
    privateKey: PrivateKey,
    sourceSatoshis?: number,
    lockingScript?: Script,
  ): {
    sign: (tx: Transaction, inputIndex: number) => Promise<UnlockingScript>;
    estimateLength: () => Promise<number>;
  } {
    return {
      sign: async (tx: Transaction, inputIndex: number) => {
        const { input, sourceTXID, sourceSatoshis: extractedSatoshis, lockingScript: extractedLockingScript, otherInputs } =
          this.extractInputInfo(tx, inputIndex, sourceSatoshis, lockingScript);

        const preimage = TransactionSignature.format({
          sourceTXID,
          sourceOutputIndex: input.sourceOutputIndex,
          sourceSatoshis: extractedSatoshis,
          transactionVersion: tx.version,
          otherInputs,
          inputIndex,
          outputs: tx.outputs,
          inputSequence: input.sequence as number,
          subscript: extractedLockingScript,
          lockTime: tx.lockTime,
          scope: this.signatureScope,
        });

        const { sigForScript, pubkeyForScript } = createSignature(privateKey, preimage, this.signatureScope);
        const { fundOutpoint, changeOutput } = this.buildFundAndChangeOutputs(tx);

        const unlockingScript = new UnlockingScript([
          // 178 empty ancestor chunks (89 A + 89 B, no miscData)
          ...createEmptyFungibleAncestorChunksSMB(),
          // 5 empty interop args
          ...scriptChunksFromBin([]), // grandparentBoltVoutIdx
          ...scriptChunksFromBin([]), // interopBoltVoutIdx
          ...scriptChunksFromBin([]), // interopPubKeyHash
          ...scriptChunksFromBin([]), // interopOutpoint
          ...scriptChunksFromBin([]), // interopParentOutpoint
          // fundOutpoint, changeOutput
          ...scriptChunksFromBin(fundOutpoint),
          ...scriptChunksFromBin(changeOutput),
          // pubKeyHash1 (hash160 of pubkey for melt P2PKH check)
          ...scriptChunksFromBin(Hash.hash160(pubkeyForScript)),
          ...scriptChunksFromBin([]), // pubKeyHash2
          ...scriptChunksFromBin([]), // nextBalanceCommit
          ...scriptChunksFromBin([]), // nextTxoType
          ...scriptChunksFromBin([]), // inputIndexN
          // sig, pubKey
          ...scriptChunksFromBin(sigForScript),
          ...scriptChunksFromBin(pubkeyForScript),
          // 6 empty CTX pieces (triggers melt path)
          ...scriptChunksFromBin([]),
          ...scriptChunksFromBin([]),
          ...scriptChunksFromBin([]),
          ...scriptChunksFromBin([]),
          ...scriptChunksFromBin([]),
          ...scriptChunksFromBin([]),
          // Compiled script logic
          ...Script.fromASM(this.UNLOCK_SCRIPT_SUFFIX).chunks,
        ]);

        return unlockingScript;
      },

      estimateLength: async () => {
        return 400;
      },
    };
  }
}
